PechinchaMarket/Models/Loja.cs
using System.ComponentModel.DataAnnotations;

namespace PechinchaMarket.Models
{
    /// <summary>
    /// Loja de um comerciante.
    /// </summary>
    public class Loja
    {
        /// <summary>
        /// id da entrada na tabela
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// morada da loja do comerciante
        /// </summary>
        [Display(Name = "Morada")]
        public string Address { get; set; }

        /// <summary>
        /// Horário de abertura da loja
        /// </summary>
        [Display(Name = "Horário de Abertura")]
        [DataType(DataType.Time)]
        public DateTime OpeningTime { get; set; }

        /// <summary>
        /// Horário de fecho da loja
        /// </summary>
        [Display(Name = "Horário de Fecho")]
        [DataType(DataType.Time)]
        public DateTime ClosingTime { get; set; }

        /// <summary>
        /// id que relaciona com o id de User
        /// </summary>
        public string UserId { get; set; }
    }
}

PechinchaMarket/Controllers/LojasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PechinchaMarket.Areas.Identity.Data;
using PechinchaMarket.Models;

namespace PechinchaMarket.Controllers
{
    public class LojasController : Controller
    {
        private readonly DBPechinchaMarketContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<PechinchaMarketUser> _userManager;

        public LojasController(DBPechinchaMarketContext context, Microsoft.AspNetCore.Identity.UserManager<PechinchaMarketUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Lojas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Loja.ToListAsync());
        }

        // GET: Lojas/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loja = await _context.Loja
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loja == null)
            {
                return NotFound();
            }

            return View(loja);
        }

        // GET: Lojas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lojas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,OpeningTime,ClosingTime")] Loja loja)
        {
            ModelState.Remove("UserId");
            if (ModelState.IsValid)
            {
                loja.Id = Guid.NewGuid();
                loja.UserId = _userManager.GetUserId(User);
                _context.Add(loja);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loja);
        }

        // GET: Lojas/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loja = await _context.Loja.FindAsync(id);
            if (loja == null)
            {
                return NotFound();
            }
            return View(loja);
        }

        // POST: Lojas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Address,OpeningTime,ClosingTime,UserId")] Loja loja)
        {
            if (id != loja.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loja);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LojaExists(loja.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loja);
        }

        // GET: Lojas/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loja = await _context.Loja
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loja == null)
            {
                return NotFound();
            }

            return View(loja);
        }

        // POST: Lojas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var loja = await _context.Loja.FindAsync(id);
            if (loja != null)
            {
                _context.Loja.Remove(loja);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LojaExists(Guid id)
        {
            return _context.Loja.Any(e => e.Id == id);
        }
    }
}

PechinchaMarket/Views/Lojas/Create.cshtml
@model PechinchaMarket.Models.Loja

@{
    ViewData["Title"] = "Create";
}
<link href="~/css/loja.css" rel="stylesheet" />

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_WfRY526MlBgsOxALrNXdf0qNl9m-Zk4&loading=async&libraries=places&callback=initAutocomplete" async defer></script>
<script>
    function initAutocomplete() {
        var input = document.getElementById('location-input');
        var autocomplete = new google.maps.places.Autocomplete(input, {
            types: ['geocode'], // Optional: restricts the search to addresses
            componentRestrictions: { country: 'PT' }, // Restricts the results to Portugal
            language: 'pt' // Set language to Portuguese
        });
        autocomplete.setFields(['address_components', 'formatted_address']);
    }
</script>

<a class="back" onclick="goBack()"></a>
<h2>Adicionar Loja</h2>
<div class="content">
    <div class="col-md-4 small-padding-left">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" id="location-input" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningTime" class="control-label"></label>
                <input asp-for="OpeningTime" class="form-control" />
                <span asp-validation-for="OpeningTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingTime" class="control-label"></label>
                <input asp-for="ClosingTime" class="form-control" />
                <span asp-validation-for="ClosingTime" class="text-danger"></span>
            </div>
            <div class="small-padding-right small-padding-top">
                <input type="submit" value="Criar Loja" class="blue-button" />
            </div>
               
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PechinchaMarket/Views/Lojas/Edit.cshtml
@model PechinchaMarket.Models.Loja

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/loja.css" rel="stylesheet" />

<a class="back" onclick="goBack()"></a>
<h2>Editar Loja</h2>
<div class="content">
    <div class="col-md-4 small-padding-left">
        <form asp-action="Edit">
            <input type="hidden" name="produtoId" value="@Model.Id" />
            <input type="hidden" name="UserId" value="@Model.UserId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" value="@Model.Address"  />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningTime" class="control-label"></label>
                <input asp-for="OpeningTime" class="form-control" />
                <span asp-validation-for="OpeningTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingTime" class="control-label"></label>
                <input asp-for="ClosingTime" class="form-control" />
                <span asp-validation-for="ClosingTime" class="text-danger"></span>
            </div>
            <div class="small-padding-top">
                <input type="submit" value="Guardar Alterações" class="blue-button" />
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PechinchaMarket/Views/Lojas/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using PechinchaMarket.Areas.Identity.Data
@model IEnumerable<PechinchaMarket.Models.Loja>
@inject UserManager<PechinchaMarketUser> UserManager

@{
    ViewData["Title"] = "Index";
    var counter = 0;
}
<script src="~/js/site.js"></script>
<link href="~/css/loja.css" rel="stylesheet" />

<h1 class="small-padding smaller-padding-left">Lojas</h1>

<body>
<a href="@Url.Action("Create", "Lojas")" class="floating-button"></a>

<div class="small-padding small-padding-top">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OpeningTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClosingTime)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.UserId == UserManager.GetUserId(User))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OpeningTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ClosingTime)
                        </td>
                        <td>
                                <a class="img-edit" asp-action="Edit" asp-route-id="@item.Id"></a>
                                <a class="img-trash" onclick="deletePopup(@counter);"></a>
                        </td>
                    </tr>

                        <div class="new-page display-none" id="delete-popup-@counter">
                            <div class="smaller-page column-container center-x-flex center-y-flex shrink-flex edges-flex">
                                <div class="edges-flex max-width">
                                    <div class="title unselectable-text">Eliminar Loja</div>
                                    <div class="cross-button" onclick="deletePopup(@counter);"></div>
                                </div>

                                <div class="column-container max-height  edges-flex max-width">
                                    <span class=" small-margin-top">Tem certeza que deseja eliminar esta Loja?</span>
                                    <div class="center-x-flex">
                                       <p>Na seguinte morada, @Html.DisplayFor(modelItem => item.Address) </p>
                                    </div>

                                    <div class="row-container right-flex max-width ">
                                        <form asp-action="Delete" method="post" asp-route-id=@item.Id>

                                            <div class="delete-div  small-padding-right2">

                                                <button class="pechincha-button delete-button-color bigger-button" type="submit"> Eliminar Loja</button>

                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>

                        </div>
                        counter++;
                }           
            }
        </tbody>
    </table>

</div>
</body>
<script>
    document.addEventListener("DOMContentLoaded", 
        tooltipmsg("Nesta pagina poderá analisar, editar, criar e eleminar todas as suas lojas.", "", "")
    );

    function deletePopup(text) {
        document.body.classList.toggle('no-overflow');
        chooseimage = document.getElementById("delete-popup-" + text);
        chooseimage.classList.toggle('display-none');
    }
</script>