PechinchaMarket/Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace PechinchaMarket.Models
{

    /// <summary>
    /// classe de produto
    /// </summary>
    public class Produto
    {
        /// <summary>
        /// id da entrada na tabela
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// O nome do produto
        /// </summary>
        [Display(Name = "Nome")]
        public string Name {  get; set; }

        /// <summary>
        /// O nome da marca do produto
        /// </summary>
        [Display(Name = "Marca")]
        public string Brand { get; set; }

        /// <summary>
        /// Uma imagem do produto
        /// </summary>
        [Display(Name = "Imagem")]
        public byte[] Image { get; set; }

        /// <summary>
        /// Peso do Produto
        /// </summary>
        [Display(Name = "Peso")]
        public float? Weight { get; set; }

        /// <summary>
        /// Medida de Unidade do produto
        /// </summary>
        [EnumDataType(typeof(UnidadeMedida))]
        public UnidadeMedida Unidade { get; set; }

        /// <summary>
        ///  Estado de aprovação do produto
        /// </summary>
        [EnumDataType(typeof(Estado))]
        public Estado? ProdEstado { get; set; }

        /// <summary>
        /// Categoria do Produto
        /// </summary>
        [Display(Name = "Categoria")]
        [EnumDataType(typeof(Categoria))]
        public Categoria ProdCategoria { get; set; }

        /// <summary>
        /// Uma lista de tabelas de relação Lojas-Produtos onde o produto se encontra
        /// </summary>
        public List<ProdutoLoja>? ProdutoLojas { get; set; }

    }
}

PechinchaMarket/Controllers/ProdutosController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using PechinchaMarket.Areas.Identity.Data;
using PechinchaMarket.Models;
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using EllipticCurve.Utils;
using System.Text.RegularExpressions;
using static System.Net.Mime.MediaTypeNames;
using Aspose.Pdf;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PechinchaMarket.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly DBPechinchaMarketContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<PechinchaMarketUser> _userManager;

        public ProdutosController(DBPechinchaMarketContext context, Microsoft.AspNetCore.Identity.UserManager<PechinchaMarketUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }



        // GET: Produtos
        public async Task<IActionResult> Index()
        {

            var userId = _userManager.GetUserId(User);
            var comerciante = await _context.Comerciante.FirstOrDefaultAsync(c => c.UserId == userId);


            if (comerciante != null)
            {
                var products = await _context.Produto
                .Where(x => x.ProdutoLojas.Any(pl => pl.Loja.UserId.Equals(comerciante.UserId)))
                .Include(x => x.ProdutoLojas)
                    .ThenInclude(x => x.Loja)
                .ToListAsync();

                return View(products);
            }
            else
            {
                
                return NotFound();
            }
        }


        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto.Include(x => x.ProdutoLojas)
                    .ThenInclude(x => x.Loja)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }
                
        public async Task<IActionResult> ShowImage(int? id)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto
                .FirstOrDefaultAsync(m => m.Id == id);

            return File(produto.Image, "image/jpg");
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            ViewData["Shops"] = _context.Loja.Where(l => l.UserId == _userManager.GetUserId(User));
            return View();
        }

        /// <summary>
        /// Função Create - Utilizada quando o comerciante pretende criar um novo produto
        /// </summary>
        /// <param name="produto">novo produto a adicionar à base de dados</param>
        /// <param name="file">imagem do produto</param>
        /// <param name="price">conjunto de preços para definir estes nos ProdutoLojas definidos</param>
        /// <returns>View da lista dos produtos do comerciante</returns>
        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Brand,Image,Weight,Unidade,ProdCategoria")] Produto produto, IFormFile file, float[] price)
        {
            ModelState.Remove("Image");
            if (ModelState.IsValid)
            {
                var memoryStreamImg = new MemoryStream();

                await file.CopyToAsync(memoryStreamImg);

                var userId = _userManager.GetUserId(User);
                List<Loja> lojas = (from l in _context.Loja where l.UserId == userId select l).ToList();
                if (!lojas.IsNullOrEmpty())
                {
                    List<ProdutoLoja> ProdL = new List<ProdutoLoja>();
                    
                    for(int i = 0; i< lojas.Count;i++)
                    {
                        int pi = i+1;
                        var p = new ProdutoLoja { Price = price[pi], Loja = lojas[i] };
                        ProdL.Add(p);
                    }
                    
                    

                    produto.ProdEstado = Estado.InAnalysis;
                    produto.Image = memoryStreamImg.ToArray();
                    produto.ProdutoLojas = ProdL;

                    _context.Add(produto);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["alertMessage"] = "Nao existe nenhuma loja";
                    return View(produto);
                }
                
            }
            return View(produto);
        }

        /// <summary>
        /// Função Edit - utilizada quando o comerciante pretende editar um produto
        /// </summary>
        /// <param name="id">id do produto</param>
        /// <returns>View com opções de edição do produto</returns>
        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = _context.Produto.Include(x => x.ProdutoLojas).ThenInclude(x => x.Loja).Where(x => x.Id == id).FirstOrDefault();

            return View(model);
        }


        /// <summary>
        /// Função Edit httpPost - utilizada quando o comerciante realiza submit do formulário de edição de um produto
        /// </summary>
        /// <param name="id">id do produto</param>
        /// <param name="produto">informação do produto a ser atualizada</param>
        /// <param name="price">novo preço do produto</param>
        /// <param name="discount">desconto do produto</param>
        /// <param name="file">imagem do produto</param>
        /// <param name="duration">duração do desconto</param>
        /// <returns>View da lista de produtos</returns>
        // POST: Produtos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Brand,Image,Weight,Unidade,ProdEstado,ProdCategoria")] Produto produto, float[] price, float[] discount, IFormFile file, string[] duration)
        {
            if (id != produto.Id)
            {
                return NotFound();
            }

            ModelState.Remove("file");
            ModelState.Remove("discount");
            ModelState.Remove("duration");
            ModelState.Remove("Image");

            if (ModelState.IsValid)
            {
                try
                {
                    var produtoToUpdate = await _context.Produto
                        .Include(p => p.ProdutoLojas)
                        .FirstOrDefaultAsync(p => p.Id == id);

                    if (produtoToUpdate == null)
                    {
                        return NotFound();
                    }

                    if (file != null)
                    {
                        // Atualizar a imagem do produto, se for o caso
                        using (var memoryStream = new MemoryStream())
                        {
                            await file.CopyToAsync(memoryStream);
                            produtoToUpdate.Image = memoryStream.ToArray();
                            _context.Update(produtoToUpdate);
                        }
                    }

                    // Atualizar o campo Price
                    if (price != null)
                    {
                        for (int i = 0; i < produtoToUpdate.ProdutoLojas.Count && i < price.Length; i++)
                        {
                            var currentProdutoLoja = produtoToUpdate.ProdutoLojas[i];
                            currentProdutoLoja.Price = price[i];
                            _context.Update(currentProdutoLoja);
                        }
                    }

                    // Atualizar o campo Discount e Duration
                    if (discount != null && duration != null)
                    {
                        for (int i = 0; i < produtoToUpdate.ProdutoLojas.Count && i < discount.Length && i < duration.Length; i++)
                        {
                            var currentProdutoLoja = produtoToUpdate.ProdutoLojas[i];
                            currentProdutoLoja.Discount = discount[i];

                            if (!string.IsNullOrEmpty(duration[i]) && duration[i].Contains("-"))
                            {
                                var durationParts = duration[i].Split('-');
                                if (durationParts.Length >= 2 && DateTime.TryParse(durationParts[0].Trim(), out DateTime inicioPromocao) && DateTime.TryParse(durationParts[1].Trim(), out DateTime fimPromocao))
                                {
                                    // Atualizar os campos StartDiscount e EndDiscount
                                    currentProdutoLoja.StartDiscount = Convert.ToDateTime(inicioPromocao.ToString("yyyy-MM-ddTHH:mm:ss.fffffff"));
                                    currentProdutoLoja.EndDiscount = Convert.ToDateTime(fimPromocao.ToString("yyyy-MM-ddTHH:mm:ss.fffffff"));

                                    _context.Update(currentProdutoLoja);
                                }
                                else
                                {

PechinchaMarket/Views/Produtos/Details.cshtml
@using System.Drawing
@model PechinchaMarket.Models.Produto

@{
    ViewData["Title"] = "Details";
}
<link href="~/css/produto.css" rel="stylesheet" />

<a class="back" onclick="goBack()"></a>
<h2>@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Brand)</h2>

<body class="gradiante2-secondary-color background-height">
    <div class="medium-padding-left medium-padding-top medium-padding">
        <div class="addProductLeft">
            <div style="display:none" id="produtoId">
                @Html.DisplayFor(model => model.Id)
            </div>
            <div class="form-group">
                <label style="font-weight: bold">Nome: </label> 
                @Html.DisplayFor(model => model.Name)
            </div>
            <div class="form-group">
                <label style="font-weight: bold">Marca: </label>
                @Html.DisplayFor(model => model.Brand)
            </div>
            <div class="form-group">
                <label style="font-weight: bold">Categoria: </label>
                @Html.DisplayFor(model => model.ProdCategoria)
            </div>
            <label style="font-weight: bold">Imagem: </label>
            <div class="form-group">
                <img id="image_preview" src="@Url.Action("ShowImage", "Produtos", new { id = @Model.Id})" alt="your image" width="250px" height="250px" class="imagePlaceholder" />
            </div>
        </div>
    </div>
    <div class="bottom small-padding-top medium-padding-left">
        <div>
            
            <table class="shopsTable medium-padding-left">
                <h4>Lojas: </h4>
                <thead>
                    <tr>
                        <th>
                            Morada
                        </th>
                        <th>
                            Preço
                        </th>
                        <th>
                            Desconto
                        </th>
                        <th>
                            Duração
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.ProdutoLojas != null)
                    {
                        @foreach (var pl in Model.ProdutoLojas)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => pl.Loja.Address)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => pl.Price)€
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => pl.Discount)%
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => pl.StartDiscount) - @Html.DisplayFor(modelItem => pl.EndDiscount)
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>        
    </div>
</body>

PechinchaMarket/Views/Produtos/Index.cshtml
@model List<Produto>

@{
    ViewData["Title"] = "Index";
    var counter = 0;

}
<script src="~/js/site.js"></script>
<link href="~/css/listaProduto.css" rel="stylesheet" />
<h1 class="smaller-padding smaller-padding-left">Produtos</h1>

<body>

<div class="container-box"> 

        <span class="coluna" id="publicados-tab">
            <h2><a id ="publicados"> Produtos Publicados</a></h2>
        </span>

        <span class="coluna" id="pendentes-tab">
            <h2><a id="pendentes"> Produtos Pendentes</a></h2>
        </span>

        <span class="coluna" id="rejeitados-tab">
            <h2><a id="rejeitados"> Produtos Rejeitados</a></h2>
        </span>
       
</div>

    <section class="containers">
        <a onclick="addPopup()" class="floating-button"></a>
    
        <div id="publicados-products" style="display:flex; flex-wrap:wrap; width:100%">
            @if(Model.Where(p => p.ProdEstado == Estado.Approved).Count() == 0){
                <div class="container">
                    <span class="empty"></span>
                </div>
                <p class="center-text max-width">Não há produtos publicados.</p>

            }
            @foreach (var item in Model.Where(p => p.ProdEstado == Estado.Approved).GroupBy(p => p.Id)
            .Select(g => g.First()))
            {
                <div class="card" asp-action="Details" asp-route-id=@item.Id>
                    <a asp-action="Details" asp-route-id=@item.Id>
                        <div class="card-image">
                            <img src='@Url.Action( "ShowImage", "Manager", new { id = item.Id})' />
                        </div>
                        <p>@Html.DisplayFor(modelItem => item.Name)</p>
                        <p>@Html.DisplayFor(modelItem => item.Brand)</p>
                        <p>@Html.DisplayFor(modelItem => item.ProdutoLojas.FirstOrDefault().Price)€/@item.Unidade</p>
                    </a>
                    <div class="options">
                        <p><a class="img-edit" asp-action="Edit" asp-route-id="@item.Id"></a> </p>
                        <p><a class="img-trash" onclick="deletePopup(@counter);"></a></p>
                    </div>

                        <div class="new-page display-none" id="delete-popup-@counter">
                            <div class="small-page column-container center-x-flex center-y-flex shrink-flex edges-flex">
                                <div class="edges-flex max-width">
                                    <div class="title unselectable-text">Eliminar Produto</div>
                                    <div class="cross-button" onclick="deletePopup(@counter);"></div>
                                </div>

                                <div class="column-container max-height edges-flex max-width">
                                    <span class="small-margin-top">Tem certeza que deseja eliminar este produto?</span>
                                    <div class="center-x-flex">
                                        <div class="center-y-flex small-gap-y column-container wrap-flex small-page-product">
                                            <img class="huge-image" src='@Url.Action( "ShowImage", "Manager", new { id = item.Id})' />
                                            <span>@Html.DisplayFor(modelItem => item.Name) - @Html.DisplayFor(modelItem => item.Brand)</span>
                                        </div>
                                    </div>

                                    <div class="row-container right-flex max-width">
                                        <form asp-action="Delete" asp-route-id="@item.Id">
                                            <button class="pechincha-button delete-button-color row-container bigger-button" type="submit">Eliminar</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <div>

                </div>
                counter++;
            }
        </div>

        <div id="pendentes-products" style="display:none; flex-wrap:wrap; width:100%">
            @if (Model.Where(p => p.ProdEstado == Estado.InAnalysis).Count() == 0)
            {
                <div class="container">
                    <span class="empty"></span>
                </div>
                <p class="center-text max-width">Não há produtos pendentes.</p>

            }
            @foreach (var item in Model.Where(p => p.ProdEstado == Estado.InAnalysis).GroupBy(p => p.Id)
            .Select(g => g.First()))
            {
                <div class="card">
                    <a asp-action="Details" asp-route-id=@item.Id>
                        <div class="card-image">
                            <img src='@Url.Action("ShowImage", "Manager", new { id = item.Id})' />
                        </div>
                        <p>@Html.DisplayFor(modelItem => item.Name)</p>
                        <p>@Html.DisplayFor(modelItem => item.Brand)</p>
                        <p>@Html.DisplayFor(modelItem => item.ProdutoLojas.FirstOrDefault().Price)€/@item.Unidade</p>
                   </a>
                    <div class="options">
                        <p><a class="img-trash" onclick="deletePopup(@counter);"></a></p>
                    </div>

                    <div class="new-page display-none" id="delete-popup-@counter">
                        <div class="small-page column-container center-x-flex center-y-flex shrink-flex edges-flex">
                            <div class="edges-flex max-width">
                                <div class="title unselectable-text">Eliminar Produto</div>
                                <div class="cross-button" onclick="deletePopup(@counter);"></div>
                            </div>

                            <div class="column-container max-height  edges-flex max-width">
                                <span class=" small-margin-top">Tem certeza que deseja eliminar este produto?</span>
                                <div class="center-x-flex">
                                    <div class="center-y-flex small-gap-y column-container wrap-flex small-page-product">
                                        <img class="huge-image" src='@Url.Action( "ShowImage", "Manager", new { id = item.Id})' />
                                        <span>@Html.DisplayFor(modelItem => item.Name) - @Html.DisplayFor(modelItem => item.Brand)</span>

                                    </div>
                                </div>

                                <div class="row-container right-flex max-width ">
                                    <form asp-action="Delete" asp-route-id=@item.Id>
                                        <button class="pechincha-button  delete-button-color row-container bigger-button" type="submit">Eliminar</button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div>

                </div>
                counter++;
            }
        </div>
        
        <div id="rejeitados-products" style="display:none; width: 100%;">
            <div class="container">
                <span class="coming-soon"></span>
            </div>
        </div>

        <div class="new-page display-none" id="add-popup">
            <div class="smaller-page column-container center-x-flex center-y-flex shrink-flex edges-flex">
                <div class="edges-flex max-width">
                    <div class="title unselectable-text">Adicionar Produto[s]</div>
                    <div class="cross-button" onclick="addPopup();"></div>
                </div>

                <div class="column-container max-height  edges-flex max-width">
                    <span class=" small-margin-top">Deseja adicionar um produtos ou vários?</span>
                    <div class="center-x-flex">
                        <div class="center-y-flex small-gap-y column-container wrap-flex small-page-product">
                            <a href="@Url.Action("Create", "Produtos")" class="create-product-type-button">Criar um produto</a>
                            <a href="@Url.Action("AddMultiplesProducts", "Produtos")" class="create-product-type-button">Criar vários produtos</a>
               

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
  
</body>

<script>
    document.addEventListener("DOMContentLoaded",
        tooltipmsg("Nesta pagina poderá analisar, editar, criar e eliminar todos os seus produtos.", "", "")
    );
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        document.getElementById('publicados-tab').addEventListener('click', function () {
            document.getElementById("publicados-tab").classList.add("active-tab");
            document.getElementById("pendentes-tab").classList.remove("active-tab");
            document.getElementById('publicados-products').style.display = 'flex';
            document.getElementById('pendentes-products').style.display = 'none';
            document.getElementById('rejeitados-products').style.display = 'none';
        });

        document.getElementById('pendentes-tab').addEventListener('click', function () {
            document.getElementById("publicados-tab").classList.remove("active-tab");
            document.getElementById("pendentes-tab").classList.add("active-tab");
            document.getElementById('publicados-products').style.display = 'none';
            document.getElementById('pendentes-products').style.display = 'flex';
            document.getElementById('rejeitados-products').style.display = 'none';
        });

        document.getElementById('rejeitados-tab').addEventListener('click', function () {
            document.getElementById("publicados-tab").classList.remove("active-tab");
            document.getElementById("pendentes-tab").classList.remove("active-tab");
            document.getElementById("rejeitados-tab").classList.add("active-tab");
            document.getElementById('publicados-products').style.display = 'none';
            document.getElementById('pendentes-products').style.display = 'none';
            document.getElementById('rejeitados-products').style.display = 'flex';
        });

        function deletePopup(text) {
            document.body.classList.toggle('no-overflow');
            chooseimage = document.getElementById("delete-popup-" + text);
            chooseimage.classList.toggle('display-none');
        }

        function addPopup() {
            document.body.classList.toggle('no-overflow');
            chooseimage = document.getElementById("add-popup");
            chooseimage.classList.toggle('display-none');
        }
    </script>
}

PechinchaMarket/Views/Produtos/ProductsInAnalysis.cshtml
@model IEnumerable<Tuple<PechinchaMarket.Models.Produto, PechinchaMarket.Models.ProdutoLoja>>

@{
    ViewData["Title"] = "Index";
}
<link href="~/css/listaProduto.css" rel="stylesheet" />
<h1>Produtos</h1>


<body>

    <div class="container-box">

        <span class="coluna">
            <h2> <a asp-action="Index"> Produtos Publicados </a> </h2>
        </span>

        <span class="coluna-selecionada">
            <h2> <a asp-action="ProductsInAnalysis"> Produtos Pendentes</a></h2>
        </span>

    </div>

    <section class="containers">
       

        @foreach (var item in Model)
        {
            <div class="card">

                <div class="card-image">
                    <img src='@Url.Action( "ShowImage", "Manager", new { id = item.Item1.Id

                  })' />
                </div>
                <p>@Html.DisplayFor(modelItem => item.Item1.Name)</p>
                <p>@Html.DisplayFor(modelItem => item.Item1.Brand)</p>
                <p>@Html.DisplayFor(modelItem => item.Item2.Price)€/@item.Item1.Unidade</p>

                <div class="options">
                    <p><a class="img-edit" asp-action="Edit" asp-route-id="@item.Item1.Id"></a> </p>
                    <p><a class="img-trash" asp-action="Delete" asp-route-id=@item.Item1.Id></a></p>
                </div>
            </div>




        }




    </section>
</body>