PechinchaMarket/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PechinchaMarket.Areas.Identity.Data;
using PechinchaMarket.Models;
using PechinchaMarket.Services;

namespace PechinchaMarket.Controllers
{
    public class ManagerController : Controller
    {
        private readonly DBPechinchaMarketContext _context;

        public ManagerController(DBPechinchaMarketContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Metódo para mostrar a lista de comerciantes não aprovados
        /// </summary>
        /// <returns>View da lista dos comerciantes que ainda não foram aprovados</returns>
        public async Task<ActionResult> NonConfirmedList()
        {

            var model = _context.Comerciante
       .Join(_context.Users,
           comerciante => comerciante.UserId,
           user => user.Id,
           (comerciante, user) => new Tuple<Comerciante, PechinchaMarketUser>(comerciante, user))
       .ToList();

            return View(model);
        }

        /// <summary>
        /// Metódo para mostrar a lista de produtos não aprovados
        /// </summary>
        /// <returns>View da lista de produtos que ainda não foram aprovados</returns>
        public async Task<ActionResult> NonAprovedProducts()
        {
            return View(await _context.Produto.ToListAsync());
        }

        /// <summary>
        /// Metódo para mostrar os detalhes de um comerciante
        /// </summary>
        /// <param name="id">id do comerciante</param>
        /// <returns>View com as informações do comerciante</returns>
        public async Task<IActionResult> DetailsComerciante(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = _context.Comerciante.Where(comerciante => comerciante.Id == id)
        .Join(_context.Users,
           comerciante => comerciante.UserId,
           user => user.Id,
           (comerciante, user) => new Tuple<Comerciante, PechinchaMarketUser>(comerciante, user));

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        /// <summary>
        /// Metódo para mostrar os detalhes de um produto
        /// </summary>
        /// <param name="id">id do produto</param>
        /// <returns>View com as informações do produto</returns>
        public async Task<IActionResult> DetailsProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = _context.Produto.Where(produto => produto.Id == id)
       .Join(_context.ProdutoLoja,
           produto => produto.Id,
           prodLoja => prodLoja.Produto.Id,
           (produto, prodLoja) => new Tuple<Produto, ProdutoLoja>(produto, prodLoja))
       .ToList();

            return View(model);
        }

        /// <summary>
        /// Metódo para aprovar um comerciante       
        /// </summary>
        /// <param name="id">id do comerciante</param>
        /// <returns>Redireciona para a view de comerciantes por aprovar</returns>
        [HttpPost, ActionName("Aprove")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AproveConfirmed(Guid? id)
        {
            var comerciante = await _context.Comerciante.FindAsync(id);
            var utilizador = await _context.Users.FirstOrDefaultAsync(m => m.Id == comerciante.UserId);
            if (comerciante != null)
            {
                comerciante.isApproved = true;

                if(utilizador != null) {
                    utilizador.EmailConfirmed = true;
                    EmailSender emailSender = new EmailSender();
                    await emailSender.SendEmail("Seu cadastro foi aceito",utilizador.Email,comerciante.Name, "Estamos felizes em informar que seu registo como comerciante na plataforma PechinchaMarket foi aceito",_context);
                   
            

                }
            }
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(NonConfirmedList));

        }

        /// <summary>
        /// Metódo para aprovar um produto
        /// </summary>
        /// <param name="id">id do produto</param>
        /// <returns>Redireciona para a view de produtos por aprovar</returns>
        [HttpPost, ActionName("ApproveProduct")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AproveConfirmedProduct(int? id)
        {
            var produto = await _context.Produto.FindAsync(id);
            if (produto != null)
            {
                produto.ProdEstado = 0;
            }
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(NonAprovedProducts));

        }

        /// <summary>
        /// Metódo para reprovar um comerciante
        /// </summary>
        /// <param name="id">id do comerciante</param>
        /// <returns>Redireciona para a view de comerciantes por aprovar</returns>
        [HttpPost, ActionName("Reprove")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReproveConfirmed(Guid? id)
        {
            var comerciante = await _context.Comerciante.FindAsync(id);
            var utilizador = await _context.Users.FirstOrDefaultAsync(m => m.Id == comerciante.UserId);
            var utilizadorId = await _context.Users.FindAsync(utilizador.Id);

            if (comerciante != null)
            {
        
             
                if (utilizador != null)
                {
                    EmailSender emailSender = new EmailSender();
                    await emailSender.SendEmail("Seu cadastro foi recusado", utilizador.Email, comerciante.Name, "Lamentamos informar que seu registo como comerciante na plataforma PechinchaMarket não foi aceito",_context);
                    _context.Comerciante.Remove(comerciante);
                    _context.Users.Remove(utilizador);
                }
            
                


            }
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(NonConfirmedList));

        }

        //Mudar o estado do produto para reporvado
        /// <summary>
        /// Metódo para reprovar um produto
        /// </summary>
        /// <param name="id">id do produto</param>
        /// <returns>Redireciona para a view de produtos por aprovar</returns>
        [HttpPost, ActionName("ReproveProduct")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReproveConfirmedProduct(int? id)
        {
            var produto = await _context.Produto.FindAsync(id);
            if (produto != null)
            {
                produto.ProdEstado = (Estado?)1;
            }
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(NonAprovedProducts));

        }

        /// <summary>
        /// Metódo para mostrar o logo do comerciante
        /// </summary>
        /// <param name="id">id do comerciante</param>
        /// <returns>Imagem do logo</returns>
        public async Task<IActionResult> ShowLogo(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var comerciante = await _context.Comerciante
                .FirstOrDefaultAsync(m => m.Id == id);

            return File(comerciante.logo, "image/jpg");
        }

        /// <summary>
        /// Metódo para mostrar a imagem do produto
        /// </summary>
        /// <param name="id">id do produto</param>
        /// <returns>Imagem do produto</returns>
        public async Task<IActionResult> ShowImage(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var produto = await _context.Produto
                .FirstOrDefaultAsync(m => m.Id == id);

            return File(produto.Image, "image/jpg");
        }

        /// <summary>
        /// Metódo para mostrar o documento
        /// </summary>
        /// <param name="id">id do comerciante</param>
        /// <returns>Documento de vericidade do comerciante</returns>
        public async Task<IActionResult> ShowDocument(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comerciante = await _context.Comerciante
                .FirstOrDefaultAsync(m => m.Id == id);

            return File(comerciante.document, "application/pdf");
        }

        /// <summary>
        /// Metódo que envia um email para o comerciante 
        /// </summary>
        /// <param name="email"></param>
        /// <param name="subject"></param>
        /// <param name="body"></param>
        /// <returns></returns>
        private async Task<bool> SendEmailAsync(string email, string subject, string body)
        {


            try
            {
                MailMessage message = new MailMessage();
                SmtpClient smtpClient = new SmtpClient();
                message.From = new MailAddress("pechinchamarket@outlook.com");
                message.To.Add(email);
                message.Subject = subject;
                message.IsBodyHtml = true;
                message.Body = body;

                smtpClient.Port = 587;
                smtpClient.Host = "smtp-mail.outlook.com";


                smtpClient.EnableSsl = true;
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new NetworkCredential("pechinchamarket@outlook.com", "Pechinchamos");
                smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtpClient.Send(message);
                return true;
            }

PechinchaMarket/Views/Search/AddToList.cshtml
@model List<Produto>

@{
    ViewData["Title"] = "Adicionar Produto na Lista";

    IEnumerable<ListaProdutos> listas = ViewData["Listas"] as IEnumerable<ListaProdutos>;
    IEnumerable<Loja> lojas = ViewData["Lojas"] as IEnumerable<Loja>;
    IEnumerable<Produto> produtos = ViewData["ProdutosSemelhantes"] as IEnumerable<Produto>;
    IEnumerable<Comerciante> comerciantes = ViewData["Comerciante"] as IEnumerable<Comerciante>;

}
<script src="~/js/site.js"></script>
<link href="~/css/resultadoPesquisa.css" rel="stylesheet" />

<div style="display:none" id="produtoId">
    @Html.DisplayFor(model => model.FirstOrDefault().Id)
</div>
<a class="back" onclick="goBack()"></a>
<div id="mensagem">
</div>
<div class="row-container center-x-flex center-y-flex screen-height">
 
    <span class="imagem-produto" style="background-image: url('@Url.Action("ShowImage", "Manager", new { id = @Model.Select(x => x.Id).FirstOrDefault()})');">  </span>
    
    <div class="fit-content-width medium-padding-left">
       <div class="info">
            <div>
               <h3> @Html.DisplayFor(model => model.FirstOrDefault().Name)
                    @Html.DisplayFor(model => model.FirstOrDefault().Brand) -
                    @if (Model.Any())
                    {
                        var userId = Model.Select(x => x.ProdutoLojas.FirstOrDefault().Loja.UserId).FirstOrDefault();
                        var name = comerciantes.Where(c => c.UserId == userId).First().Name;
                        @name
                    }
                </h3>
            </div>

            <div class="discounts">
                @if (ViewBag.PrecoExibicao != null)
                {
                    <span class="discounted-price-text">
                        @ViewBag.PrecoExibicao.ToString()€/@Html.DisplayFor(model => model.FirstOrDefault().Unidade)
                    </span>
                    <span class="price-text">
                        <s>@Html.DisplayFor(model => model.FirstOrDefault().ProdutoLojas.FirstOrDefault().Price)€/ @Html.DisplayFor(model => model.FirstOrDefault().Unidade)</s> <!-- Riscar o preço sem desconto -->
                    </span>
                    <span class="discount-text">
                        Desconto de @Html.DisplayFor(model => model.FirstOrDefault().ProdutoLojas.FirstOrDefault().Discount)%
                    </span>
                }
                else
                {
                    <span class="price-text default">
                        @Html.DisplayFor(model => model.FirstOrDefault().ProdutoLojas.FirstOrDefault().Price)€/@Html.DisplayFor(model => model.FirstOrDefault().Unidade)
                    </span>
                }
            </div>
       </div>
                
        <div class="acoes">

            @if (User.Identity.IsAuthenticated)
            {
                <div class="quantity">
                    <input class="numberstyle" type="number" min="1" max="99" step="1" value="1" id="quantityInput"> @Html.DisplayFor(model => model.FirstOrDefault().Unidade)
                </div>
                                         
                <div>
                    <input name="nome" type="text" id="name" onclick="showListas()" autocomplete="off" placeholder="Selecione uma Lista"/>
                    <div id="listas" style="display: none">
                        <table class="lista-item" id="item">
                            @foreach (ListaProdutos l in listas)
                            {
                                <tr>
                                    <td onclick="selectLista('@l.name','@l.Id')" class="black">
                                        @Html.DisplayFor(modelItem => l.name)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            
                <form asp-action="AddProduct">
                    <input name="id" type="hidden" asp-for="@Model.FirstOrDefault().ProdutoLojas.FirstOrDefault().Id, quantityValue, nameValue" />
                    <input name="nome" type="hidden" id="nameValue"/>
                    <input name="quantityValue" type="hidden" dirname="quantity" id="quantityValue" />
                    <input type="submit" value="Adicionar à lista" class="button-add" onclick="updateQuantity(); updateName()" />
                </form>
            }
            <div>
                <input type="submit" value="Lojas" class="button-shops" onclick="showLojas()" />
            </div>
             
            <div class="lojas" id="lojas">
                <a class="img-close" onclick="showLojas()"></a>
                <h2>Lojas</h2>
                @foreach (Loja l in lojas)
                {
                    <div>
                        @Html.DisplayFor(modelItem => l.Address)
                    </div>
                    <div>
                        @Html.DisplayFor(modelItem => l.OpeningTime) - @Html.DisplayFor(modelItem => l.ClosingTime)
                    </div>
                    <hr />
                }
            </div>

        </div>

    </div>

</div>
<div class="produtos-semelhantes"
    <div class="items-semelhantes">
        @if(produtos != null)
        {
            @foreach (Produto l in produtos)
            {
                 <div class="produto-semelhante">
                    <a asp-action="AddToList" asp-route-id="@l.Id">
                        <span class="imagem" style="background-image: url('@Url.Action("ShowImage", "Manager", new { id = l.Id})"></span>
                        @Html.DisplayFor(modelItem => l.Name) - @Html.DisplayFor(modelItem => l.Brand)
                    </a>
                </div>
            }
        }        
    </div>
</div>


@section Scripts{
    <script>
        document.addEventListener("DOMContentLoaded", 
            tooltipmsg("Nesta página, poderá obter os detalhes do produto, bem como adicioná-lo a uma lista desejada.", "", "")
        );

        function updateQuantity() {
            var quantity = document.getElementById('quantityInput').value;
            document.getElementById('quantityValue').value = quantity;
        }

        function updateName() {
            var name = document.getElementById('name').value;
            document.getElementById('nameValue').value = name;
        }

        function showLojas() {
            var x = document.getElementById("lojas");
            if (x.style.display == "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }

        function showListas() {
            var x = document.getElementById("listas");
            if (x.style.display == "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }

        function selectLista(name, id) {
            var x = document.getElementById("name");
            x.value = name;
            showListas();
        }

        document.addEventListener('DOMContentLoaded', function () {
            const specificDiv = document.getElementById('mensagem');

            function displayMessage(statusMessage) {
                const statusElement = document.createElement('div');
                statusElement.classList.add('alert', 'alert-success', 'status-message');
                statusElement.textContent = statusMessage;

                specificDiv.innerHTML = '';
                specificDiv.appendChild(statusElement);

                const displayTime = 5000;
                setTimeout(() => {
                    statusElement.style.display = 'none';
                }, displayTime);
            }

            const statusMessage = '@TempData["StatusMessage"]';

            if (statusMessage) {
                displayMessage(statusMessage);
            }
        });
        
    </script>
}